# ###################################646f75627420796f7572206f776e206578697374656e6365###################################
#
#              """          settings.py
#       -\-    _|__
#        |\___/  . \        Created on 23 Sep. 2026 at 18:37
#        \     /(((/        by hmelica
#         \___/)))/         hmelica@student.42.fr
#
# ######################################################################################################################

"""
Django settings for qrprotecDB project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'QRPROTEC_SECRET_KEY', 'django-insecure-3rq#5ry)%ta2t^##wfge$#(j%@3nicnz1vh5vwffphe1z7o*(8'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('QRPROTEC_DEBUG', '1') == '1'

# Liste separee par des virgules, ex: QRPROTEC_ALLOWED_HOSTS=inventaire.example.com,192.168.1.10
ALLOWED_HOSTS = [host for host in os.environ.get('QRPROTEC_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',') if host]
# Hotes acceptes en plus en mode DEBUG uniquement (tests depuis un telephone sur le reseau local)
if DEBUG:
    ALLOWED_HOSTS += [host for host in os.environ.get('QRPROTEC_DEBUG_HOSTS', '192.168.1.201,10.80.79.134').split(',') if host]

# Derriere un reverse proxy HTTPS (nginx, caddy...) pour l'API publique
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


def _env_list(name, default):
    return [value.strip() for value in os.environ.get(name, default).split(',') if value.strip()]


# Configuration propre a QRProtec
QRPROTEC = {
    # Base des URLs encodees dans les QR codes (lots, badges, paquets). Changer ici (ou via la variable
    # d'environnement) suffit : le front reconnait les QR codes quel que soit le domaine.
    'PUBLIC_BASE_URL': os.environ.get('QRPROTEC_PUBLIC_BASE_URL', 'https://example.com/'),
    'PUBLIC_API_ADDRESS': os.environ.get('QRPROTEC_PUBLIC_API_ADDRESS', '0.0.0.0'),
    'PUBLIC_API_PORT': int(os.environ.get('QRPROTEC_PUBLIC_API_PORT', '8000')),
    'LOCAL_API_ADDRESS': os.environ.get('QRPROTEC_LOCAL_API_ADDRESS', '127.0.0.1'),
    'LOCAL_API_PORT': int(os.environ.get('QRPROTEC_LOCAL_API_PORT', '8001')),
    # Adresses clientes acceptees par l'API locale ('*' pour tout accepter, a eviter)
    'LOCAL_API_ALLOWED_ADDRESSES': _env_list('QRPROTEC_LOCAL_API_ALLOWED_ADDRESSES', '127.0.0.1,::1'),
    # Jeton optionnel exige dans l'en-tete X-QRProtec-Token sur l'API locale
    'LOCAL_API_TOKEN': os.environ.get('QRPROTEC_LOCAL_API_TOKEN', ''),
    # Role des requetes qui n'ont pas ete recues par `manage.py serve` (runserver, wsgi par defaut)
    'DEFAULT_API_ROLE': os.environ.get('QRPROTEC_DEFAULT_API_ROLE', 'public'),
    'USER_KEY_VALIDITY_DAYS': 365,
    'LOT_KEY_VALIDITY_DAYS': int(os.environ.get('QRPROTEC_LOT_KEY_VALIDITY_DAYS', '3650')),
    # Un item non perime est considere disparu apres ce nombre de verifs sans etre scanne
    'MISSING_AFTER_VERIFS': int(os.environ.get('QRPROTEC_MISSING_AFTER_VERIFS', '3')),
    # Envoi des SMS dans la requete (1) ou dans un thread (0, defaut)
    'SMS_SYNC': os.environ.get('QRPROTEC_SMS_SYNC', '0') == '1',
    # Contact annonce aux services de notifications web (VAPID) : mailto:... ou https://... (defaut : PUBLIC_BASE_URL)
    'WEB_PUSH_SUBJECT': os.environ.get('QRPROTEC_WEB_PUSH_SUBJECT', ''),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
    'UNAUTHENTICATED_USER': None,
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'inventory.middleware.ApiRoleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qrprotecDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qrprotecDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('QRPROTEC_DB_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
