[project]
name = "qrprotec"
version = "0.1.0"
description = ""
authors = [
    {name = "Hippolyte Melica",email = "hippolytemelica@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.1.1,<7.0.0)",
    "djangorestframework (>=3.18.1,<4.0.0)"
]

[tool.poetry]
packages = [{include = "qrprotec", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
