# Generated by Django 6.1.1 on 2026-09-29 16:13

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "type",
                    models.CharField(
                        editable=False, max_length=6, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("min_quantity", models.PositiveIntegerField(default=0)),
                ("perissable", models.BooleanField(default=False)),
                ("default_pack_size", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="LotType",
            fields=[
                (
                    "type",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(blank=True, default="", max_length=32)),
                ("version", models.PositiveIntegerField(default=1)),
                ("valid_version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Secouristes",
            fields=[
                (
                    "matricule",
                    models.CharField(
                        editable=False, max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=32)),
                ("prenom", models.CharField(max_length=32)),
                ("key", models.CharField(blank=True, max_length=32, null=True)),
                ("key_expires", models.DateField(blank=True, null=True)),
                ("privileged", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "name",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("last_sequence", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ItemsPacks",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=14, primary_key=True, serialize=False
                    ),
                ),
                ("peremption", models.DateField(blank=True, null=True)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
                (
                    "item_type",
                    models.ForeignKey(
                        db_column="type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.itemtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotSequence",
            fields=[
                (
                    "lot_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="inventory.lottype",
                    ),
                ),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Lots",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "verif_key",
                    models.CharField(
                        default=inventory.models.generate_key, max_length=32
                    ),
                ),
                (
                    "verif_key_expires",
                    models.DateField(
                        default=inventory.models.default_lot_key_expiration
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(max_length=32)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "last_used_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_verif", models.DateTimeField(blank=True, null=True)),
                (
                    "last_verif_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "last_verif_while",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("is_sealed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=64)),
                ("name_short", models.CharField(max_length=16)),
                (
                    "lot_type",
                    models.ForeignKey(
                        db_column="type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.lottype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SealedPacks",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=8, primary_key=True, serialize=False
                    ),
                ),
                ("peremption", models.DateField(blank=True, null=True)),
                ("count", models.PositiveIntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(max_length=32)),
                ("opened", models.DateTimeField(blank=True, null=True)),
                ("opened_by", models.CharField(blank=True, default="", max_length=32)),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.itemtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "iid",
                    models.CharField(
                        editable=False, max_length=22, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Present"),
                            ("missing", "Disparu"),
                            ("replaced", "Remplace"),
                            ("deleted", "Supprime manuellement"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("missed_verifs", models.PositiveIntegerField(default=0)),
                ("last_seen", models.DateTimeField()),
                ("last_seen_by", models.CharField(max_length=64)),
                (
                    "last_seen_while",
                    models.CharField(
                        choices=[
                            ("create", "Creation"),
                            ("verif", "Verification"),
                            ("add", "Ajout a un lot"),
                            ("remove", "Retour en stock"),
                            ("delete", "Suppression manuelle"),
                            ("restore", "Restauration"),
                            ("open", "Ouverture de paquet"),
                        ],
                        max_length=8,
                    ),
                ),
                ("added", models.DateTimeField()),
                ("added_by", models.CharField(max_length=32)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, default="", max_length=32)),
                (
                    "deleted_reason",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.itemspacks",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.lots",
                    ),
                ),
                (
                    "sealed_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.sealedpacks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verifs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("by", models.CharField(max_length=64)),
                ("complete", models.BooleanField(default=False)),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("missing_count", models.PositiveIntegerField(default=0)),
                ("expired_count", models.PositiveIntegerField(default=0)),
                ("replaced_count", models.PositiveIntegerField(default=0)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.lots",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerifItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("missing", "Absent"),
                            ("replaced", "Remplace"),
                        ],
                        default="present",
                        max_length=8,
                    ),
                ),
                ("expired", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.items",
                    ),
                ),
                (
                    "verif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inventory.verifs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.itemtype",
                    ),
                ),
                (
                    "lot_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="inventory.lottype",
                    ),
                ),
            ],
            options={
                "unique_together": {("lot_type", "item_type")},
            },
        ),
    ]
