# Generated by Django 6.1.1 on 2026-09-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("stock_low", models.BooleanField(default=True)),
                ("verif_problem", models.BooleanField(default=True)),
                ("seal_broken", models.BooleanField(default=True)),
                ("expired_daily", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SmsRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("user", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemtype",
            name="low_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lotrequirements",
            name="location",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="lots",
            name="seal_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="lots",
            name="seal_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="lots",
            name="sealed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lots",
            name="sealed_by",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="lots",
            name="unsealed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lots",
            name="unsealed_by",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
