# Generated by Django 6.1.1 on 2026-09-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="lots",
            name="restocked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lots",
            name="restocked_by",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="lots",
            name="restocked_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lots",
            name="verif_recommended",
            field=models.BooleanField(default=False),
        ),
    ]
