# Generated by Django 6.1.1 on 2026-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_restock"),
    ]

    operations = [
        migrations.AddField(
            model_name="secouristes",
            name="pin_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="secouristes",
            name="pin_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="secouristes",
            name="pin_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
