# Generated by Django 6.1.1 on 2026-10-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="lots",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="inventory.lots",
            ),
        ),
        migrations.AddField(
            model_name="lottype",
            name="storage",
            field=models.BooleanField(default=False),
        ),
    ]
