# Generated by Django 6.1.1 on 2026-10-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_sub_lots_storage"),
        ("inventory", "0006_web_push"),
    ]

    operations = []
