# Generated by Django 6.1.1 on 2026-10-01 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_merge_sub_lots_web_push"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "last_address",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("revoked", models.BooleanField(default=False)),
            ],
        ),
    ]
