# Generated by Django 6.1.1 on 2026-10-02 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def reconstruct(apps, schema_editor):
    """Reconstitue les absences passees depuis les verifs : la premiere absence d'un item dans une suite de verifs
    compte comme une utilisation (ou un jet s'il etait perime), annulee si l'item a ete revu ensuite."""
    Items = apps.get_model('inventory', 'Items')
    VerifItem = apps.get_model('inventory', 'VerifItem')
    ItemMovement = apps.get_model('inventory', 'ItemMovement')
    entries = (VerifItem.objects.select_related('verif', 'item__pack')
               .order_by('item_id', 'verif__datetime', 'id'))
    movements = []
    current = None
    absence = None

    def close(item):
        # absence encore ouverte mais item revu depuis (deplace, ajoute a un lot) : il a ete retrouve
        if absence is not None and item.status == 'active' and item.missed_verifs == 0:
            absence.cancelled = item.last_seen
            absence.cancelled_by = item.last_seen_by

    for entry in entries.iterator(chunk_size=2000):
        item = entry.item
        if current is None or current.iid != item.iid:
            if current is not None:
                close(current)
            current = item
            absence = None
        verif = entry.verif
        common = {'item_id': item.iid, 'item_type_id': item.pack.item_type_id, 'at': verif.datetime, 'by': verif.by,
                  'from_lot_id': verif.lot_id, 'verif_id': verif.id, 'reconstructed': True}
        if entry.result == 'missing':
            if absence is None:
                absence = ItemMovement(kind='discarded' if entry.expired else 'used', **common)
                movements.append(absence)
        else:
            if absence is not None:
                absence.cancelled = verif.datetime
                absence.cancelled_by = verif.by
                absence = None
            if entry.result == 'replaced':
                movements.append(ItemMovement(kind='replaced', **common))
    if current is not None:
        close(current)
    ItemMovement.objects.bulk_create(movements, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_pin_blocked_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("move", "Déplacement"),
                            ("used", "Utilisé"),
                            ("discarded", "Jeté (périmé)"),
                            ("replaced", "Remplacé"),
                            ("deleted", "Supprimé"),
                            ("restored", "Restauré"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("by", models.CharField(blank=True, default="", max_length=64)),
                ("cancelled", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reconstructed", models.BooleanField(default=False)),
                (
                    "from_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.lots",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.items",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.itemtype",
                    ),
                ),
                (
                    "to_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.lots",
                    ),
                ),
                (
                    "verif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.verifs",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["item", "kind", "cancelled"],
                        name="inventory_i_item_id_ecacfb_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(reconstruct, migrations.RunPython.noop),
    ]
