# Generated by Django 6.1.1 on 2026-10-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_types_archive_unique_tear_off"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declared_identity", models.BooleanField(default=False)),
            ],
        ),
    ]
