# Generated by Django 6.1.1 on 2026-10-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_server_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="lots",
            name="seal_open_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
