# Generated by Django 6.1.1 on 2026-10-05 06:30

from collections import Counter, defaultdict

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Count

MAX_LISTED_ITEMS = 500


def plural(count, word):
    return f"{count} {word}{'s' if count > 1 else ''}"


def types_summary(names):
    return ', '.join(f'{count} × {name}' for name, count in sorted(Counter(names).items()))


def reconstruct(apps, schema_editor):
    """Reconstitue le journal des operations depuis les donnees anterieures : verifs, mouvements d'items
    (reassorts, retraits, suppressions), receptions, paquets ouverts, derniers scellages et ouvertures de scelle
    de chaque lot (les precedents ne sont pas conserves), creations de lots et de types de lots."""
    Operation = apps.get_model('inventory', 'Operation')
    Verifs = apps.get_model('inventory', 'Verifs')
    ItemMovement = apps.get_model('inventory', 'ItemMovement')
    Items = apps.get_model('inventory', 'Items')
    Lots = apps.get_model('inventory', 'Lots')
    LotType = apps.get_model('inventory', 'LotType')
    SealedPacks = apps.get_model('inventory', 'SealedPacks')
    rows = []

    def add(kind, at, by, summary, lot=None, **details):
        if at is None:
            return
        rows.append(Operation(at=at, by=(by or '')[:64], kind=kind, lot=lot, lot_name=lot.name if lot else '',
                              summary=summary[:255], details=details, reconstructed=True))

    verif_moments = set()
    for verif in Verifs.objects.select_related('lot').iterator(chunk_size=2000):
        verif_moments.add((verif.lot_id, verif.datetime))
        counts = [(verif.present_count, 'présent'), (verif.missing_count, 'manquant'),
                  (verif.expired_count, 'périmé'), (verif.replaced_count, 'remplacé')]
        parts = ', '.join(plural(count, word) for count, word in counts if count)
        if verif.lot_id is None:
            add('stock_verif', verif.datetime, verif.by, parts or 'aucun item', verif=verif.id, complete=True)
        else:
            add('verif', verif.datetime, verif.by, ('complète' if verif.complete else 'incomplète')
                + (' : ' + parts if parts else ''), lot=verif.lot, verif=verif.id, complete=verif.complete,
                present=verif.present_count, missing=verif.missing_count, expired=verif.expired_count,
                replaced=verif.replaced_count)

    groups = defaultdict(list)
    movements = (ItemMovement.objects.filter(reconstructed=False, kind__in=['move', 'deleted', 'restored'])
                 .select_related('item', 'item_type', 'from_lot', 'to_lot').order_by('at', 'id'))
    for move in movements.iterator(chunk_size=2000):
        if move.kind == 'deleted':
            reason = move.item.deleted_reason if move.item.status == 'deleted' else ''
            add('item_delete', move.at, move.by, f'{move.item_type.name} {move.item_id}' + (f' : {reason}' if reason else ''),
                lot=move.from_lot, items=[move.item_id], reason=reason)
        elif move.kind == 'restored':
            add('item_restore', move.at, move.by, f'{move.item_type.name} {move.item_id}', lot=move.to_lot,
                items=[move.item_id])
        elif (move.to_lot_id, move.at) in verif_moments:
            continue  # item range dans le lot verifie : fait partie de la verif
        elif move.to_lot_id:
            groups[('restock', move.at, move.by, move.to_lot_id)].append(move)
        elif move.from_lot_id:
            groups[('remove', move.at, move.by, move.from_lot_id)].append(move)
    for (kind, at, by, _), moves in groups.items():
        lot = moves[0].to_lot if kind == 'restock' else moves[0].from_lot
        add(kind, at, by, types_summary(move.item_type.name for move in moves), lot=lot, count=len(moves),
            items=[move.item_id for move in moves][:MAX_LISTED_ITEMS])

    receptions = (Items.objects.values('pack__item_type__name', 'pack__item_type__perissable', 'pack__item_type_id',
                                       'pack__peremption', 'added', 'added_by', 'sealed_pack_id')
                  .annotate(count=Count('iid')))
    for batch in receptions:
        summary = f"{batch['count']} × {batch['pack__item_type__name']}"
        if batch['pack__item_type__perissable'] and batch['pack__peremption']:
            summary += f", péremption {batch['pack__peremption'].strftime('%d/%m/%Y')}"
        if batch['sealed_pack_id']:
            summary += f" (paquet fermé {batch['sealed_pack_id']})"
        add('reception', batch['added'], batch['added_by'], summary, type=batch['pack__item_type_id'],
            count=batch['count'], sealed_pack=batch['sealed_pack_id'])

    for pack in SealedPacks.objects.select_related('item_type').filter(opened__isnull=False):
        add('pack_open', pack.opened, pack.opened_by, f'{pack.count} × {pack.item_type.name} (paquet {pack.id})',
            pack=pack.id, type=pack.item_type_id, count=pack.count)

    for lot in Lots.objects.select_related('lot_type'):
        add('lot', lot.created, lot.created_by, f'lot créé ({lot.lot_type.name})', lot=lot)
        number = f'scellé n°{lot.seal_number}' if lot.seal_number else 'scellé sans numéro'
        if lot.sealed:
            add('seal', lot.sealed, lot.sealed_by, number, lot=lot, seal_number=lot.seal_number)
        if lot.unsealed:
            opened = f'scellé n°{lot.seal_number} ouvert' if lot.seal_number else 'scellé ouvert'
            add('unseal', lot.unsealed, lot.unsealed_by, opened, lot=lot, seal_number=lot.seal_number)

    for lot_type in LotType.objects.all():
        add('catalog', lot_type.created, lot_type.created_by, f'type de lot créé : {lot_type.name} ({lot_type.type})',
            type=lot_type.type)

    Operation.objects.bulk_create(rows, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_seal_open_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "by",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("verif", "Vérif"),
                            ("stock_verif", "Vérif du stock"),
                            ("restock", "Réassort"),
                            ("remove", "Retrait vers le stock"),
                            ("seal", "Scellage"),
                            ("unseal", "Ouverture de scellé"),
                            ("reception", "Réception"),
                            ("item_delete", "Suppression d'item"),
                            ("item_restore", "Restauration d'item"),
                            ("pack_open", "Ouverture de paquet"),
                            ("pack_close", "Paquet refermé"),
                            ("lot", "Gestion des lots"),
                            ("lot_key", "Étiquette privée renouvelée"),
                            ("catalog", "Types d'items et de lots"),
                            ("user", "Utilisateurs"),
                            ("settings", "Réglages"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("lot_name", models.CharField(blank=True, default="", max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("reconstructed", models.BooleanField(default=False)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.lots",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lot", "at"], name="inventory_o_lot_id_9781f7_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(reconstruct, migrations.RunPython.noop),
    ]
